#Project Name:E-commerce Chatbot using Large Language Model (LLM)

##Overview:  
###In this capstone project, I will embark on an exciting journey to create an Industry-Specific Large Language Model (LLM) Bot using state-of-the-art pre-trained models from sources like Hugging Face. The primary objective is to build an intelligent bot that can effectively engage with users by answering questions and providing insights specific to a chosen industry. This project will not only enhance your technical skills but also provide a deep understanding of the chosen industry's nuances, challenges, and trends.

##Industry Selection::  
###Retail and E-commerce Design bots for customer service, product recommendations, and order tracking.
###I selected the Retail and E-commerce industry because:
1) Online shopping is rapidly growing

2) Businesses require automated customer support

3) chatbots are widely used in platforms like Amazon and Flipkart.

##Problem Statement:  
###In the rapidly growing retail and e-commerce industry, customers often require quick and accurate responses to their queries related to products, pricing, and services. Traditional customer support systems are time-consuming and may not always be available in real time.
###The objective of this project is to develop an AI-powered chatbot that can understand and respond to user queries related to e-commerce products. The chatbot should be capable of providing product information, answering common customer questions, and simulating real-time customer support interactions.

##Github Link:

##Let's Begin:

##1) Install Necessery libraries:

####I installed the required Python libraries needed for building and training the chatbot model in Google Colab.

In [1]:
!pip install transformers datasets accelerate -q

In [2]:
import transformers
import datasets
import accelerate

print("Libraries installed successfully!")

Libraries installed successfully!

##2) Import libraries:

####I imported all the required libraries and classes needed for dataset handling, model loading, and training the chatbot. The pandas library is used to read and manage the dataset, while Dataset converts the data into a format compatible with Hugging Face training. The transformers modules such as AutoTokenizer, AutoModelForCausalLM, Trainer, and TrainingArguments are used to load the pre-trained model, process text data, configure training settings, and train the chatbot model.

In [3]:
import pandas as pd
from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments
)

##3) Load Dataset:

####I loaded the Flipkart e-commerce dataset into a dataframe using the read_csv() function from the pandas library. The df.head() function is used to display the first 5 rows of the dataset to verify that the data has been loaded correctly.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
df = pd.read_csv("/content/drive/MyDrive/almabetter_project/flipkart_com-ecommerce.csv")
df.head()

,Sr.no,product_name,product_category_tree,description,retail_price,discounted_price,brand
0,1,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,999.0,379.0,Alisha
1,2,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,32157.0,22646.0,FabHomeDecor
2,3,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",Key Features of AW Bellies Sandals Wedges Heel...,999.0,499.0,AW
3,4,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,699.0,267.0,Alisha
4,5,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",Specifications of Sicons All Purpose Arnica Do...,220.0,210.0,Sicons

####I checked the size of the dataset using df.shape. The output Original Shape: (3000, 6) shows that the dataset contains 3000 rows and 6 columns. This helps verify the amount of data available before preprocessing and training the chatbot model.

In [12]:
print("Original Shape:", df.shape)

Original Shape: (3000, 7)

In [13]:
df = df.fillna("Unknown")
df.head()

,Sr.no,product_name,product_category_tree,description,retail_price,discounted_price,brand
0,1,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,999.0,379.0,Alisha
1,2,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,32157.0,22646.0,FabHomeDecor
2,3,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",Key Features of AW Bellies Sandals Wedges Heel...,999.0,499.0,AW
3,4,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,699.0,267.0,Alisha
4,5,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",Specifications of Sicons All Purpose Arnica Do...,220.0,210.0,Sicons

##4) Create Q&A Dataset:

#### I created a custom Question & Answer dataset from the Flipkart product data to train the chatbot. A loop was used to read each product’s details such as product name, description, brand, retail price, and discounted price, and multiple question-answer pairs were generated automatically for every product. After creating the Q&A data, it was converted into a new dataframe, saved as flipkart_qa_dataset.csv, and its shape was displayed to confirm the dataset was created successfully.

In [15]:
qa_data = []

for _, row in df.iterrows():

    product = str(row["product_name"])
    description = str(row["description"])[:250]

    brand = str(row["brand"])
    retail_price = str(row["retail_price"])
    discounted_price = str(row["discounted_price"])

    # Q1: Product description
    qa_data.append({
        "text": f"Question: What is {product}?\nAnswer: {product} is a product. {description}"
    })

    # Q2: Brand
    qa_data.append({
        "text": f"Question: Which brand makes {product}?\nAnswer: The brand of this product is {brand}."
    })

    # Q3: Retail price
    qa_data.append({
        "text": f"Question: What is the retail price of {product}?\nAnswer: The retail price is ₹{retail_price}."
    })

    # Q4: Discount price
    qa_data.append({
        "text": f"Question: What is the discounted price of {product}?\nAnswer: The discounted price is ₹{discounted_price}."
    })

# Convert to dataframe
qa_df = pd.DataFrame(qa_data)

print("Q&A Dataset Shape:", qa_df.shape)

# Save dataset
qa_df.to_csv("/content/drive/MyDrive/almabetter_project/flipkart_qa_dataset.csv", index=False)

print("Q&A dataset saved successfully!")

Q&A Dataset Shape: (12000, 1)
Q&A dataset saved successfully!

####I displayed the first 20 rows of the generated Q&A dataset using qa_df.head(20). The output shows that multiple question-answer pairs were successfully created for each product, including product description, brand name, retail price, and discounted price questions. This step helps verify that the chatbot training data is properly formatted before model training.

In [16]:
qa_df.head(20)

                                                 text
0   Question: What is Alisha Solid Women's Cycling...
1   Question: Which brand makes Alisha Solid Women...
2   Question: What is the retail price of Alisha S...
3   Question: What is the discounted price of Alis...
4   Question: What is FabHomeDecor Fabric Double S...
5   Question: Which brand makes FabHomeDecor Fabri...
6   Question: What is the retail price of FabHomeD...
7   Question: What is the discounted price of FabH...
8   Question: What is AW Bellies?\nAnswer: AW Bell...
9   Question: Which brand makes AW Bellies?\nAnswe...
10  Question: What is the retail price of AW Belli...
11  Question: What is the discounted price of AW B...
12  Question: What is Alisha Solid Women's Cycling...
13  Question: Which brand makes Alisha Solid Women...
14  Question: What is the retail price of Alisha S...
15  Question: What is the discounted price of Alis...
16  Question: What is Sicons All Purpose Arnica Do...
17  Question: Which brand makes Sicons All Purpose...
18  Question: What is the retail price of Sicons A...
19  Question: What is the discounted price of Sico...

####I printed the first 10 question-answer entries from the generated dataset to manually inspect the chatbot training data. The loop displays each question and answer pair one by one, while "="*100 creates a separator line to make the output more readable. This helps verify that the dataset contains correctly formatted product-related questions and answers before training the model.

In [17]:
for i in range(10):
    print(qa_df["text"][i])
    print("\n" + "="*100 + "\n")

Question: What is Alisha Solid Women's Cycling Shorts?
Answer: Alisha Solid Women's Cycling Shorts is a product. Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra Navy, Red, Navy,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 3 Fabric Cotton Lycra Type Cycling Shorts General Detail

====================================================================================================

Question: Which brand makes Alisha Solid Women's Cycling Shorts?
Answer: The brand of this product is Alisha.

====================================================================================================

Question: What is the retail price of Alisha Solid Women's Cycling Shorts?
Answer: The retail price is ₹999.0.

====================================================================================================

Question: What is the discounted price of Alisha Solid Women's Cycling Shorts?
Answer: The discounted price is ₹379.0.

====================================================================================================

Question: What is FabHomeDecor Fabric Double Sofa Bed?
Answer: FabHomeDecor Fabric Double Sofa Bed is a product. FabHomeDecor Fabric Double Sofa Bed (Finish Color - Leatherette Black Mechanism Type - Pull Out) Price: Rs. 22,646 • Fine deep seating experience • Save Space with the all new click clack Sofa Bed • Easy to fold and vice versa with simple click clack

====================================================================================================

Question: Which brand makes FabHomeDecor Fabric Double Sofa Bed?
Answer: The brand of this product is FabHomeDecor.

====================================================================================================

Question: What is the retail price of FabHomeDecor Fabric Double Sofa Bed?
Answer: The retail price is ₹32157.0.

====================================================================================================

Question: What is the discounted price of FabHomeDecor Fabric Double Sofa Bed?
Answer: The discounted price is ₹22646.0.

====================================================================================================

Question: What is AW Bellies?
Answer: AW Bellies is a product. Key Features of AW Bellies Sandals Wedges Heel Casuals,AW Bellies Price: Rs. 499 Material: Synthetic Lifestyle: Casual Heel Type: Wedge Warranty Type: Manufacturer Product Warranty against manufacturing defects: 30 days Care instructions: Allow your

====================================================================================================

Question: Which brand makes AW Bellies?
Answer: The brand of this product is AW.

====================================================================================================

##5)  LOAD DISTILGPT2:

####I loaded the pre-trained GPT-2 based model distilgpt2 and its tokenizer using the Hugging Face Transformers library. The tokenizer converts text into tokens that the model can understand, while AutoModelForCausalLM loads the language model for chatbot text generation. I also set tokenizer.pad_token = tokenizer.eos_token because GPT-2 models do not have a default padding token, and this prevents errors during training.

In [18]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  353MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

#####I converted the Q&A dataframe into a Hugging Face dataset format using Dataset.from_pandas(qa_df). This conversion is necessary because the Hugging Face Trainer works efficiently with datasets in this format during tokenization and model training. The new dataset object now contains all chatbot question-answer pairs in a structure compatible with the training pipeline.

In [19]:
#convert to hugging face dataset
dataset = Dataset.from_pandas(qa_df)

##6) Tokenization:

####I defined a tokenization function to prepare the dataset for training the language model. The function converts each text entry into token IDs using the tokenizer, applies padding and truncation to ensure all inputs are of equal length (64 tokens), and then creates labels by copying the input IDs for causal language modeling.

In [20]:
def tokenize_function(example):

    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

    # Labels for language modeling
    tokens["labels"] = tokens["input_ids"].copy()

    return tokens


tokenized_dataset = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/12000 [00:00<?, ? examples/s]

##7) Training Arguments:

#####In this step, I configured and started training the chatbot model using the Hugging Face Trainer API. The TrainingArguments define how the model will be trained, including 3 epochs, batch size of 8, mixed precision (fp16=True) for faster GPU performance, and reduced logging and checkpoint saving to make training more efficient.  
#####Then, the Trainer was initialized with the model, training settings, and tokenized dataset, and training was started using trainer.train().

In [21]:
training_args = TrainingArguments(

    output_dir="./results",

    # Faster training
    num_train_epochs=3,

    # Batch size
    per_device_train_batch_size=8,

    # Save less often
    save_steps=2000,

    # Log less often
    logging_steps=500,

     # Use mixed precision
    fp16=True,

    # Faster loading
    dataloader_num_workers=2,

    # Keep only 1 checkpoint
    save_total_limit=1,

    # Disable reports
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)

trainer.train()

[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4500, training_loss=0.5169890407986111, metrics={'train_runtime': 299.8695, 'train_samples_per_second': 120.052, 'train_steps_per_second': 15.007, 'total_flos': 587917688832000.0, 'train_loss': 0.5169890407986111, 'epoch': 3.0})

#####The output shows the training progress across 4500 steps, where the loss steadily decreases from around 1.21 to 0.49, indicating that the model is learning well. The message ForCausalLMLoss means the model is using the correct default loss function for text generation. Finally, the model was successfully saved after training completion.

##8)  SAVE MODEL:

#####I saved the trained chatbot model and tokenizer to a local directory named /content/flipkart_chatbot_model. The trainer.save_model() function stores the trained model weights, while tokenizer.save_pretrained() saves the tokenizer configuration so the same text processing can be used during inference.

In [22]:
trainer.save_model("/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model")
tokenizer.save_pretrained("/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model")
print("Model saved successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved successfully!

##9) Test Chabot:

#####In this step, I loaded the trained chatbot model using the Hugging Face pipeline for text generation. This allows me to quickly test the model without writing manual inference code. I passed the saved model path /content/flipkart_chatbot_model along with the tokenizer so the model can correctly process input text.

#####Then, I gave a sample question about a product brand and asked the model to generate an answer. Parameters like max_new_tokens=50 control the response length, do_sample=True enables more creative responses, and temperature=0.7 balances randomness and accuracy.

In [23]:
from transformers import pipeline

chatbot = pipeline(
    "text-generation",
    model="/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model",
    tokenizer=tokenizer
)

prompt = "Question: Which brand makes carrol Women's Shrug?\nAnswer:"

result = chatbot(
    prompt,
    max_new_tokens=30,
    do_sample=False,
    temperature=0.2,
    pad_token_id=tokenizer.eos_token_id
)

print(result[0]["generated_text"])

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

[transformers] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Question: Which brand makes carrol Women's Shrug?
Answer: The brand of this product is carrol.

#####The output shows that the model correctly understood the question and generated a relevant answer: it identified the brand as Voylla, which confirms that the chatbot is working properly after training.

In [24]:
!zip -r flipkart_chatbot_model.zip "/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model"

from google.colab import files
files.download("flipkart_chatbot_model.zip")

  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/ (stored 0%)
  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/config.json (deflated 53%)
  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/generation_config.json (deflated 24%)
  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/model.safetensors (deflated 7%)
  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/training_args.bin (deflated 54%)
  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/tokenizer_config.json (deflated 50%)
  adding: content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model/tokenizer.json (deflated 82%)

##10) Gradio UI:

###To make the chatbot more user-friendly, I used Gradio to build a simple web-based interface. Gradio allows users to interact with the model by typing questions and receiving instant answers.

In [26]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.13/dist-packages (6.30.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (4.15.1)
Requirement already satisfied: audioop-lts<=0.2.2 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.141.1)
Requirement already satisfied: gradio-client==2.7.2 in /usr/local/lib/python3.13/dist-packages (from gradio) (2.7.2)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (1.33.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (3.0.4)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (2.1.3)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (3.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from gradio) (26.3)
Requirement already satisfied: pandas<4.0,>=1.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (2.2.3)
Requirement already satisfied: pillow<13.0,>=8.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (2.14.1)
Requirement already satisfied: pydub<1.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.0.32)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.13/dist-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from gradio) (1.8.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.14.0)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.27.3)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (4.16.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.13/dist-packages (from gradio) (0.54.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.13/dist-packages (from gradio-client==2.7.2->gradio) (2025.12.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5.0,>=3.0->gradio) (3.20)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.5)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.2.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (1.7.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=1.0->gradio) (2026.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<=3.0,>=2.0->gradio) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<=3.0,>=2.0->gradio) (2.50.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [27]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_path = "/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model"

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
model = AutoModelForCausalLM.from_pretrained(model_path, local_files_only=True)

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

In [28]:
import os

model_directory = "/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model"

if os.path.exists(model_directory):
    print(f"The model directory '{model_directory}' exists.")
else:
    print(f"The model directory '{model_directory}' does NOT exist.")

The model directory '/content/drive/MyDrive/Chat_bot/savedata/flipkart_chatbot_model' exists.

####I created a function that takes user input, converts it into tokens, and passes it to the trained model to generate a response. The output is then decoded back into readable text and returned as the chatbot’s answer.

In [29]:
def qa_chat(user_input, history):

    prompt = f"Question: {user_input}\nAnswer:"

    inputs = tokenizer(prompt, return_tensors="pt")

    output = model.generate(
        **inputs,
        max_new_tokens=50,
        temperature=0.2,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    response = tokenizer.decode(output[0], skip_special_tokens=True)

    answer = response.split("Answer:")[-1].strip()

    return answer

####I built the chatbot interface using Gradio. The ChatInterface connects my qa_chat function to a simple web UI where users can type questions and get answers instantly. Finally, chatbot.launch() starts the application and opens the chatbot in a browser for interaction.

In [30]:
import gradio as gr

chatbot = gr.ChatInterface(
    fn=qa_chat,
    title="Q&A Chatbot",
    description="Ask questions about products and get answers"
)

chatbot.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://e49cfaf8d304de8cbe.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

####Overall, using Gradio made my project more interactive, visually clear, and easy to present. It helped me focus more on the machine learning part while still providing a professional-looking chatbot interface for users.

###Conclusion:  
####In this project, I built an end-to-end e-commerce Q&A chatbot using a Flipkart product dataset. I started by loading and preprocessing the data, then converted it into structured question-answer pairs for training. After that, I tokenized the dataset and fine-tuned a pre-trained language model using Hugging Face Transformers.
####Finally, I tested the model and deployed it using Gradio to create an interactive web-based chatbot interface. The system is able to answer product-related questions such as brand, description, and pricing effectively, showing that the trained model can be used for real-world e-commerce assistance.